name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          modules: 'qtnetwork'
          cache: true

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
